# Generated by Django 5.2.10 on 2026-03-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'id']},
        ),
    ]
